/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "bg-void": "var(--color-bg-void)",
        "bg-abyss": "var(--color-bg-abyss)",
        "bg-elevated": "var(--color-bg-elevated)",
        "accent-core": "var(--color-accent-core)",
        "accent-core-soft": "var(--color-accent-core-soft)",
        "accent-signal": "var(--color-accent-signal)",
        "accent-signal-soft": "var(--color-accent-signal-soft)",
        "accent-rare": "var(--color-accent-rare)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-tertiary": "var(--color-text-tertiary)",
        "text-on-accent": "var(--color-text-on-accent)",
        "glass-fill": "var(--glass-fill)",
        "glass-fill-hover": "var(--glass-fill-hover)",
        "glass-border": "var(--glass-border)",
        "glass-border-strong": "var(--glass-border-strong)",
        "glass-highlight": "var(--glass-highlight)",
      },
      fontFamily: {
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: "var(--text-xs)",
        sm: "var(--text-sm)",
        base: "var(--text-base)",
        lg: "var(--text-lg)",
        xl: "var(--text-xl)",
        "2xl": "var(--text-2xl)",
        "3xl": "var(--text-3xl)",
        "4xl": "var(--text-4xl)",
        "5xl": "var(--text-5xl)",
      },
      letterSpacing: {
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        relaxed: "var(--leading-relaxed)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        24: "var(--space-24)",
        32: "var(--space-32)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        "glow-core-sm": "var(--glow-core-sm)",
        "glow-core-md": "var(--glow-core-md)",
        "glow-core-lg": "var(--glow-core-lg)",
        "glow-signal-sm": "var(--glow-signal-sm)",
        "glow-signal-md": "var(--glow-signal-md)",
        "elevation-1": "var(--shadow-elevation-1)",
        "elevation-2": "var(--shadow-elevation-2)",
        "elevation-3": "var(--shadow-elevation-3)",
      },
      backdropBlur: {
        glass: "var(--glass-blur)",
        "glass-strong": "var(--glass-blur-strong)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        "out-soft": "var(--ease-out-soft)",
        "in-out-soft": "var(--ease-in-out-soft)",
      },
      transitionDuration: {
        fast: "150ms",
        base: "300ms",
        slow: "600ms",
      },
      zIndex: {
        background: "var(--z-background)",
        content: "var(--z-content)",
        navbar: "var(--z-navbar)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
      },
      screens: {
        "3xl": "1600px",
      },
    },
  },
  plugins: [],
};